// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    name: "device",
    fields: {
      ua: "string",
      browser: "string",
      device: "string",
      devicePixelRatio: "string",
      pixelDepth: "string",
      resolution: "string"
    }
  };

}).call(this);
