// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    name: "events",
    fields: {
      device: "string",
      browser: "string",
      support: "string"
    }
  };

}).call(this);
