// Generated by CoffeeScript 1.7.1
(function() {
  var server, _http, _router, _url;

  _http = require('http');

  _router = require('./router');

  _url = require('url');

  require('./init-schema').init();

  server = function(req, resp) {
    var client;
    client = _url.parse(req.url, true);
    req.client = client;
    return _router(req, resp);
  };

  _http.createServer(server).listen(8000);

}).call(this);
