// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    client: 'mysql',
    connection: {
      host: 'localhost',
      user: 'root',
      password: '123456',
      database: 'bhmi'
    }
  };

}).call(this);
