// Generated by CoffeeScript 1.7.1
(function() {
  var _config;

  _config = require('./router-config');

  module.exports = function(req, resp) {
    var action, actionConfig, biz, client, method, pathname, reg;
    client = req.client;
    pathname = client.pathname;
    reg = /^(\/api)/;
    if (reg.test(pathname)) {
      pathname = pathname.replace(reg, '');
    }
    actionConfig = _config[pathname];
    if (!actionConfig) {
      actionConfig = _config['/404'];
    }
    biz = actionConfig.biz;
    method = actionConfig.method || 'execute';
    action = require("./biz/" + biz);
    return action[method](req, resp);
  };

}).call(this);
