// Generated by CoffeeScript 1.7.1
(function() {
  var doTest, _DeviceTest, _EventsTest;

  _DeviceTest = require('./test/device-test');

  _EventsTest = require('./test/event-test');

  doTest = function() {
    var Test, task, tasks, _i, _len, _results;
    Test = _EventsTest;
    tasks = Test.tasks();
    _results = [];
    for (_i = 0, _len = tasks.length; _i < _len; _i++) {
      task = tasks[_i];
      _results.push(Test[task]());
    }
    return _results;
  };

  doTest();

}).call(this);
