// Generated by CoffeeScript 1.7.1
(function() {
  var Readme, _fs, _path;

  _fs = require('fs');

  _path = require('path');

  Readme = (function() {
    function Readme() {}

    Readme.prototype.execute = function(req, resp) {
      var html, readmePath;
      readmePath = _path.join(__dirname, "../readme.html");
      html = _fs.readFileSync(readmePath, 'utf8');
      resp.write(html);
      return resp.end();
    };

    return Readme;

  })();

  module.exports = new Readme();

}).call(this);
